---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simple-daemon
spec:
  selector:
    matchLabels:
      name: simple-daemon
  template:
    metadata:
      labels:
        name: simple-daemon
    spec:    
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: busybox
        image: busybox
        args:
        - sleep
        - "10000"
          